export { default as MoviePage } from './MoviePage/MoviePage';
export { default as BookingSection } from './BookingSection/BookingSection';
export { default as HeroSection } from './HeroSection/HeroSection';
export { default as ReminderSection } from './ReminderSection/ReminderSection';
export { default as SynopsisSection } from './SynopsisSection/SynopsisSection';
export { default as DetailsSection } from './DetailsSection/DetailsSection';
export { default as ReviewsSection } from './ReviewsSection/ReviewsSection';
export { default as Review } from './Review/Review';
export { default as RatingSelector } from './RatingSelector/RatingSelector';
